package com.sf.dao;

import com.sf.model.Association1;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Association1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderID") String orderID, @Param("deliveryReceliptID") String deliveryReceliptID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int insert(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    List<Association1> selectAll();
}