package com.sf.model;

public class Association1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.orderID
     *
     * @mbg.generated
     */
    private String orderID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.deliveryReceliptID
     *
     * @mbg.generated
     */
    private String deliveryReceliptID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.orderID
     *
     * @return the value of association_1.orderID
     *
     * @mbg.generated
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.orderID
     *
     * @param orderID the value for association_1.orderID
     *
     * @mbg.generated
     */
    public void setOrderID(String orderID) {
        this.orderID = orderID == null ? null : orderID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.deliveryReceliptID
     *
     * @return the value of association_1.deliveryReceliptID
     *
     * @mbg.generated
     */
    public String getDeliveryReceliptID() {
        return deliveryReceliptID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.deliveryReceliptID
     *
     * @param deliveryReceliptID the value for association_1.deliveryReceliptID
     *
     * @mbg.generated
     */
    public void setDeliveryReceliptID(String deliveryReceliptID) {
        this.deliveryReceliptID = deliveryReceliptID == null ? null : deliveryReceliptID.trim();
    }
}