package com.sf.model;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carID
     *
     * @mbg.generated
     */
    private String carID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.routeID
     *
     * @mbg.generated
     */
    private String routeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carType
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carOrgin
     *
     * @mbg.generated
     */
    private String carOrgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carProDate
     *
     * @mbg.generated
     */
    private Date carProDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carBuyDate
     *
     * @mbg.generated
     */
    private Date carBuyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carCapacity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carstate
     *
     * @mbg.generated
     */
    private Boolean carstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carID
     *
     * @return the value of car.carID
     *
     * @mbg.generated
     */
    public String getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carID
     *
     * @param carID the value for car.carID
     *
     * @mbg.generated
     */
    public void setCarID(String carID) {
        this.carID = carID == null ? null : carID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.routeID
     *
     * @return the value of car.routeID
     *
     * @mbg.generated
     */
    public String getRouteID() {
        return routeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.routeID
     *
     * @param routeID the value for car.routeID
     *
     * @mbg.generated
     */
    public void setRouteID(String routeID) {
        this.routeID = routeID == null ? null : routeID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carType
     *
     * @return the value of car.carType
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carType
     *
     * @param carType the value for car.carType
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carOrgin
     *
     * @return the value of car.carOrgin
     *
     * @mbg.generated
     */
    public String getCarOrgin() {
        return carOrgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carOrgin
     *
     * @param carOrgin the value for car.carOrgin
     *
     * @mbg.generated
     */
    public void setCarOrgin(String carOrgin) {
        this.carOrgin = carOrgin == null ? null : carOrgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carProDate
     *
     * @return the value of car.carProDate
     *
     * @mbg.generated
     */
    public Date getCarProDate() {
        return carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carProDate
     *
     * @param carProDate the value for car.carProDate
     *
     * @mbg.generated
     */
    public void setCarProDate(Date carProDate) {
        this.carProDate = carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carBuyDate
     *
     * @return the value of car.carBuyDate
     *
     * @mbg.generated
     */
    public Date getCarBuyDate() {
        return carBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carBuyDate
     *
     * @param carBuyDate the value for car.carBuyDate
     *
     * @mbg.generated
     */
    public void setCarBuyDate(Date carBuyDate) {
        this.carBuyDate = carBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carCapacity
     *
     * @return the value of car.carCapacity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carCapacity
     *
     * @param carCapacity the value for car.carCapacity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carstate
     *
     * @return the value of car.carstate
     *
     * @mbg.generated
     */
    public Boolean getCarstate() {
        return carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carstate
     *
     * @param carstate the value for car.carstate
     *
     * @mbg.generated
     */
    public void setCarstate(Boolean carstate) {
        this.carstate = carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Comment
     *
     * @return the value of car.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Comment
     *
     * @param comment the value for car.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}