package com.sf.model;

public class Cityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.areaID
     *
     * @mbg.generated
     */
    private String areaID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityID
     *
     * @mbg.generated
     */
    private String cityID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.rangeID
     *
     * @mbg.generated
     */
    private String rangeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.areaName
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityName
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.areaID
     *
     * @return the value of cityarea.areaID
     *
     * @mbg.generated
     */
    public String getAreaID() {
        return areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.areaID
     *
     * @param areaID the value for cityarea.areaID
     *
     * @mbg.generated
     */
    public void setAreaID(String areaID) {
        this.areaID = areaID == null ? null : areaID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityID
     *
     * @return the value of cityarea.cityID
     *
     * @mbg.generated
     */
    public String getCityID() {
        return cityID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityID
     *
     * @param cityID the value for cityarea.cityID
     *
     * @mbg.generated
     */
    public void setCityID(String cityID) {
        this.cityID = cityID == null ? null : cityID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.rangeID
     *
     * @return the value of cityarea.rangeID
     *
     * @mbg.generated
     */
    public String getRangeID() {
        return rangeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.rangeID
     *
     * @param rangeID the value for cityarea.rangeID
     *
     * @mbg.generated
     */
    public void setRangeID(String rangeID) {
        this.rangeID = rangeID == null ? null : rangeID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.areaName
     *
     * @return the value of cityarea.areaName
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.areaName
     *
     * @param areaName the value for cityarea.areaName
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityName
     *
     * @return the value of cityarea.cityName
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityName
     *
     * @param cityName the value for cityarea.cityName
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}