package com.sf.model;

import java.util.Date;

public class Deliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.deliveryReceliptID
     *
     * @mbg.generated
     */
    private String deliveryReceliptID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    private Date makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.State
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.deliveryReceliptID
     *
     * @return the value of deliveryreceipt.deliveryReceliptID
     *
     * @mbg.generated
     */
    public String getDeliveryReceliptID() {
        return deliveryReceliptID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.deliveryReceliptID
     *
     * @param deliveryReceliptID the value for deliveryreceipt.deliveryReceliptID
     *
     * @mbg.generated
     */
    public void setDeliveryReceliptID(String deliveryReceliptID) {
        this.deliveryReceliptID = deliveryReceliptID == null ? null : deliveryReceliptID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.startCity
     *
     * @return the value of deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.startCity
     *
     * @param startCity the value for deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.endCity
     *
     * @return the value of deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.endCity
     *
     * @param endCity the value for deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.midCity
     *
     * @return the value of deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.midCity
     *
     * @param midCity the value for deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.makeDate
     *
     * @return the value of deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.makeDate
     *
     * @param makeDate the value for deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.State
     *
     * @return the value of deliveryreceipt.State
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.State
     *
     * @param state the value for deliveryreceipt.State
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.Comment
     *
     * @return the value of deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.Comment
     *
     * @param comment the value for deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}