package com.sf.model;

public class Deliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePID
     *
     * @mbg.generated
     */
    private String dePID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgID
     *
     * @mbg.generated
     */
    private String mgID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePName
     *
     * @mbg.generated
     */
    private String dePName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.provinceName
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.cityName
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgName
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePTel
     *
     * @mbg.generated
     */
    private String dePTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    private String dePAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePID
     *
     * @return the value of deliveryplace.dePID
     *
     * @mbg.generated
     */
    public String getDePID() {
        return dePID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePID
     *
     * @param dePID the value for deliveryplace.dePID
     *
     * @mbg.generated
     */
    public void setDePID(String dePID) {
        this.dePID = dePID == null ? null : dePID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgID
     *
     * @return the value of deliveryplace.mgID
     *
     * @mbg.generated
     */
    public String getMgID() {
        return mgID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgID
     *
     * @param mgID the value for deliveryplace.mgID
     *
     * @mbg.generated
     */
    public void setMgID(String mgID) {
        this.mgID = mgID == null ? null : mgID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePName
     *
     * @return the value of deliveryplace.dePName
     *
     * @mbg.generated
     */
    public String getDePName() {
        return dePName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePName
     *
     * @param dePName the value for deliveryplace.dePName
     *
     * @mbg.generated
     */
    public void setDePName(String dePName) {
        this.dePName = dePName == null ? null : dePName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.provinceName
     *
     * @return the value of deliveryplace.provinceName
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.provinceName
     *
     * @param provinceName the value for deliveryplace.provinceName
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.cityName
     *
     * @return the value of deliveryplace.cityName
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.cityName
     *
     * @param cityName the value for deliveryplace.cityName
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgName
     *
     * @return the value of deliveryplace.mgName
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgName
     *
     * @param mgName the value for deliveryplace.mgName
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePTel
     *
     * @return the value of deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public String getDePTel() {
        return dePTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePTel
     *
     * @param dePTel the value for deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public void setDePTel(String dePTel) {
        this.dePTel = dePTel == null ? null : dePTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePAddr
     *
     * @return the value of deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public String getDePAddr() {
        return dePAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePAddr
     *
     * @param dePAddr the value for deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public void setDePAddr(String dePAddr) {
        this.dePAddr = dePAddr == null ? null : dePAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.Comment
     *
     * @return the value of deliveryplace.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.Comment
     *
     * @param comment the value for deliveryplace.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}