package com.sf.model;

import java.math.BigDecimal;

public class Deliveryrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.rangeID
     *
     * @mbg.generated
     */
    private String rangeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.dePID
     *
     * @mbg.generated
     */
    private String dePID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.areaID
     *
     * @mbg.generated
     */
    private String areaID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.rangeName
     *
     * @mbg.generated
     */
    private String rangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.rangeID
     *
     * @return the value of deliveryrange.rangeID
     *
     * @mbg.generated
     */
    public String getRangeID() {
        return rangeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.rangeID
     *
     * @param rangeID the value for deliveryrange.rangeID
     *
     * @mbg.generated
     */
    public void setRangeID(String rangeID) {
        this.rangeID = rangeID == null ? null : rangeID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.dePID
     *
     * @return the value of deliveryrange.dePID
     *
     * @mbg.generated
     */
    public String getDePID() {
        return dePID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.dePID
     *
     * @param dePID the value for deliveryrange.dePID
     *
     * @mbg.generated
     */
    public void setDePID(String dePID) {
        this.dePID = dePID == null ? null : dePID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.areaID
     *
     * @return the value of deliveryrange.areaID
     *
     * @mbg.generated
     */
    public String getAreaID() {
        return areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.areaID
     *
     * @param areaID the value for deliveryrange.areaID
     *
     * @mbg.generated
     */
    public void setAreaID(String areaID) {
        this.areaID = areaID == null ? null : areaID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.rangeName
     *
     * @return the value of deliveryrange.rangeName
     *
     * @mbg.generated
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.rangeName
     *
     * @param rangeName the value for deliveryrange.rangeName
     *
     * @mbg.generated
     */
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName == null ? null : rangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.deliveryPrice
     *
     * @return the value of deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.deliveryPrice
     *
     * @param deliveryPrice the value for deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.Comment
     *
     * @return the value of deliveryrange.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.Comment
     *
     * @param comment the value for deliveryrange.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}