package com.sf.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mqID
     *
     * @mbg.generated
     */
    private String mqID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.roleID
     *
     * @mbg.generated
     */
    private String roleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerName
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerPsd
     *
     * @mbg.generated
     */
    private String managerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerSex
     *
     * @mbg.generated
     */
    private String managerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mqID
     *
     * @return the value of manager.mqID
     *
     * @mbg.generated
     */
    public String getMqID() {
        return mqID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mqID
     *
     * @param mqID the value for manager.mqID
     *
     * @mbg.generated
     */
    public void setMqID(String mqID) {
        this.mqID = mqID == null ? null : mqID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.roleID
     *
     * @return the value of manager.roleID
     *
     * @mbg.generated
     */
    public String getRoleID() {
        return roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.roleID
     *
     * @param roleID the value for manager.roleID
     *
     * @mbg.generated
     */
    public void setRoleID(String roleID) {
        this.roleID = roleID == null ? null : roleID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerName
     *
     * @return the value of manager.managerName
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerName
     *
     * @param managerName the value for manager.managerName
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerPsd
     *
     * @return the value of manager.managerPsd
     *
     * @mbg.generated
     */
    public String getManagerPsd() {
        return managerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerPsd
     *
     * @param managerPsd the value for manager.managerPsd
     *
     * @mbg.generated
     */
    public void setManagerPsd(String managerPsd) {
        this.managerPsd = managerPsd == null ? null : managerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerSex
     *
     * @return the value of manager.managerSex
     *
     * @mbg.generated
     */
    public String getManagerSex() {
        return managerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerSex
     *
     * @param managerSex the value for manager.managerSex
     *
     * @mbg.generated
     */
    public void setManagerSex(String managerSex) {
        this.managerSex = managerSex == null ? null : managerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Tel
     *
     * @return the value of manager.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Tel
     *
     * @param tel the value for manager.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Address
     *
     * @return the value of manager.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Address
     *
     * @param address the value for manager.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Comment
     *
     * @return the value of manager.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Comment
     *
     * @param comment the value for manager.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}