package com.sf.model;

import java.math.BigDecimal;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderID
     *
     * @mbg.generated
     */
    private String orderID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.carID
     *
     * @mbg.generated
     */
    private String carID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cuID
     *
     * @mbg.generated
     */
    private String cuID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPName
     *
     * @mbg.generated
     */
    private String postPName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPTel
     *
     * @mbg.generated
     */
    private String postPTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPAddr
     *
     * @mbg.generated
     */
    private String postPAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPName
     *
     * @mbg.generated
     */
    private String getPName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPTel
     *
     * @mbg.generated
     */
    private String getPTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPAddr
     *
     * @mbg.generated
     */
    private String getPAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsName
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsWeight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderType
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderState
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.deliveryPrice
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalPrice
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderID
     *
     * @return the value of orders.orderID
     *
     * @mbg.generated
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderID
     *
     * @param orderID the value for orders.orderID
     *
     * @mbg.generated
     */
    public void setOrderID(String orderID) {
        this.orderID = orderID == null ? null : orderID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.carID
     *
     * @return the value of orders.carID
     *
     * @mbg.generated
     */
    public String getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.carID
     *
     * @param carID the value for orders.carID
     *
     * @mbg.generated
     */
    public void setCarID(String carID) {
        this.carID = carID == null ? null : carID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cuID
     *
     * @return the value of orders.cuID
     *
     * @mbg.generated
     */
    public String getCuID() {
        return cuID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cuID
     *
     * @param cuID the value for orders.cuID
     *
     * @mbg.generated
     */
    public void setCuID(String cuID) {
        this.cuID = cuID == null ? null : cuID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPName
     *
     * @return the value of orders.postPName
     *
     * @mbg.generated
     */
    public String getPostPName() {
        return postPName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPName
     *
     * @param postPName the value for orders.postPName
     *
     * @mbg.generated
     */
    public void setPostPName(String postPName) {
        this.postPName = postPName == null ? null : postPName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPTel
     *
     * @return the value of orders.postPTel
     *
     * @mbg.generated
     */
    public String getPostPTel() {
        return postPTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPTel
     *
     * @param postPTel the value for orders.postPTel
     *
     * @mbg.generated
     */
    public void setPostPTel(String postPTel) {
        this.postPTel = postPTel == null ? null : postPTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPAddr
     *
     * @return the value of orders.postPAddr
     *
     * @mbg.generated
     */
    public String getPostPAddr() {
        return postPAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPAddr
     *
     * @param postPAddr the value for orders.postPAddr
     *
     * @mbg.generated
     */
    public void setPostPAddr(String postPAddr) {
        this.postPAddr = postPAddr == null ? null : postPAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPName
     *
     * @return the value of orders.getPName
     *
     * @mbg.generated
     */
    public String getGetPName() {
        return getPName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPName
     *
     * @param getPName the value for orders.getPName
     *
     * @mbg.generated
     */
    public void setGetPName(String getPName) {
        this.getPName = getPName == null ? null : getPName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPTel
     *
     * @return the value of orders.getPTel
     *
     * @mbg.generated
     */
    public String getGetPTel() {
        return getPTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPTel
     *
     * @param getPTel the value for orders.getPTel
     *
     * @mbg.generated
     */
    public void setGetPTel(String getPTel) {
        this.getPTel = getPTel == null ? null : getPTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPAddr
     *
     * @return the value of orders.getPAddr
     *
     * @mbg.generated
     */
    public String getGetPAddr() {
        return getPAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPAddr
     *
     * @param getPAddr the value for orders.getPAddr
     *
     * @mbg.generated
     */
    public void setGetPAddr(String getPAddr) {
        this.getPAddr = getPAddr == null ? null : getPAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsName
     *
     * @return the value of orders.goodsName
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsName
     *
     * @param goodsName the value for orders.goodsName
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsWeight
     *
     * @return the value of orders.goodsWeight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsWeight
     *
     * @param goodsWeight the value for orders.goodsWeight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderType
     *
     * @return the value of orders.orderType
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderType
     *
     * @param orderType the value for orders.orderType
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderState
     *
     * @return the value of orders.orderState
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderState
     *
     * @param orderState the value for orders.orderState
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.transportPrice
     *
     * @return the value of orders.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.transportPrice
     *
     * @param transportPrice the value for orders.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportPrice(BigDecimal transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.deliveryPrice
     *
     * @return the value of orders.deliveryPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.deliveryPrice
     *
     * @param deliveryPrice the value for orders.deliveryPrice
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalPrice
     *
     * @return the value of orders.totalPrice
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalPrice
     *
     * @param totalPrice the value for orders.totalPrice
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Comment
     *
     * @return the value of orders.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Comment
     *
     * @param comment the value for orders.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}