package com.sf.model;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.provinceID
     *
     * @mbg.generated
     */
    private String provinceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.provinceName
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.provinceID
     *
     * @return the value of province.provinceID
     *
     * @mbg.generated
     */
    public String getProvinceID() {
        return provinceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.provinceID
     *
     * @param provinceID the value for province.provinceID
     *
     * @mbg.generated
     */
    public void setProvinceID(String provinceID) {
        this.provinceID = provinceID == null ? null : provinceID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.provinceName
     *
     * @return the value of province.provinceName
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.provinceName
     *
     * @param provinceName the value for province.provinceName
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}