package com.sf.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleID
     *
     * @mbg.generated
     */
    private String roleID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleID
     *
     * @return the value of role.roleID
     *
     * @mbg.generated
     */
    public String getRoleID() {
        return roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleID
     *
     * @param roleID the value for role.roleID
     *
     * @mbg.generated
     */
    public void setRoleID(String roleID) {
        this.roleID = roleID == null ? null : roleID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param roleName the value for role.roleName
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.Comment
     *
     * @return the value of role.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.Comment
     *
     * @param comment the value for role.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}