package com.sf.model;

import java.math.BigDecimal;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeID
     *
     * @mbg.generated
     */
    private String routeID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.cityID
     *
     * @mbg.generated
     */
    private String cityID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.provinceID
     *
     * @mbg.generated
     */
    private String provinceID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeName
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startProvice
     *
     * @mbg.generated
     */
    private String startProvice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startCity
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endProvince
     *
     * @mbg.generated
     */
    private String endProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endCity
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midProvince
     *
     * @mbg.generated
     */
    private String midProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midCity
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeID
     *
     * @return the value of route.routeID
     *
     * @mbg.generated
     */
    public String getRouteID() {
        return routeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeID
     *
     * @param routeID the value for route.routeID
     *
     * @mbg.generated
     */
    public void setRouteID(String routeID) {
        this.routeID = routeID == null ? null : routeID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.cityID
     *
     * @return the value of route.cityID
     *
     * @mbg.generated
     */
    public String getCityID() {
        return cityID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.cityID
     *
     * @param cityID the value for route.cityID
     *
     * @mbg.generated
     */
    public void setCityID(String cityID) {
        this.cityID = cityID == null ? null : cityID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.provinceID
     *
     * @return the value of route.provinceID
     *
     * @mbg.generated
     */
    public String getProvinceID() {
        return provinceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.provinceID
     *
     * @param provinceID the value for route.provinceID
     *
     * @mbg.generated
     */
    public void setProvinceID(String provinceID) {
        this.provinceID = provinceID == null ? null : provinceID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeName
     *
     * @return the value of route.routeName
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeName
     *
     * @param routeName the value for route.routeName
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startProvice
     *
     * @return the value of route.startProvice
     *
     * @mbg.generated
     */
    public String getStartProvice() {
        return startProvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startProvice
     *
     * @param startProvice the value for route.startProvice
     *
     * @mbg.generated
     */
    public void setStartProvice(String startProvice) {
        this.startProvice = startProvice == null ? null : startProvice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startCity
     *
     * @return the value of route.startCity
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startCity
     *
     * @param startCity the value for route.startCity
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endProvince
     *
     * @return the value of route.endProvince
     *
     * @mbg.generated
     */
    public String getEndProvince() {
        return endProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endProvince
     *
     * @param endProvince the value for route.endProvince
     *
     * @mbg.generated
     */
    public void setEndProvince(String endProvince) {
        this.endProvince = endProvince == null ? null : endProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endCity
     *
     * @return the value of route.endCity
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endCity
     *
     * @param endCity the value for route.endCity
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midProvince
     *
     * @return the value of route.midProvince
     *
     * @mbg.generated
     */
    public String getMidProvince() {
        return midProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midProvince
     *
     * @param midProvince the value for route.midProvince
     *
     * @mbg.generated
     */
    public void setMidProvince(String midProvince) {
        this.midProvince = midProvince == null ? null : midProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midCity
     *
     * @return the value of route.midCity
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midCity
     *
     * @param midCity the value for route.midCity
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.transportPrice
     *
     * @return the value of route.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.transportPrice
     *
     * @param transportPrice the value for route.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportPrice(BigDecimal transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.Comment
     *
     * @return the value of route.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.Comment
     *
     * @param comment the value for route.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}